comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
<p>language: R</p>
<p>sudo: false</p>
<p>cache: packages</p>
<p>after_success:</p>
- Rscript -e 'covr::codecov()'
